### PR TITLE
Full implementation of calibre custom columns

### PR DESCRIPTION
**Pull request by Mikescher**
Hi,

Over the last few weeks I worked quite a bit on this code to support custom columns.
It was mostly intended for my own server, but I think it can be useful for other people too (like everyone who has custom columns in calibre).
And after I tested everything for a few days I think this can be merged back to your repo 
(if you want it :blush:).

##### Implementation of missing CustomColumnTypes

 - CustomColumnTypeText
 - CustomColumnTypeSeries
 - CustomColumnTypeEnumeration
 - CustomColumnTypeDate
 - CustomColumnTypeRating
 - CustomColumnTypeBool
 - CustomColumnTypeInteger
 - CustomColumnTypeFloat
 - CustomColumnTypeComment

I changed pretty much the whole structure in customcolumns.php. There is now an class for every CustomColumn Type derived from the class `CustomColumnType`.

All the important methods are implemented in these classes (like `getQuery()` or `getAllCustomValues()`)

I tried to document all public methods that I wrote in this class and add PHPDoc hints to the classes and methods.

The only ColumnType that I didn't implement is the composite type.
These data are not really stored in the database but calculated by calibre on the fly. We would need to implement the whole calibre composite syntax to support them. And with every calibre update it could break.
So It think it's not really worth it (and it doesn't sound like fun...)

You can add all columns as a row in the index page except the comment column (because this is a long text with formatting and everything, it never makes sense to search for identical values there).
I can imagine that it also rarely makes sense to filter by text or float columns, but the possibility is there and if someone adds these columns to the config array I imagine he has reasons to do so (for example when he uses always only one of a limited set of texts).

##### PHPDoc comments

I added a whole bunch of PHPDoc comments. Not everywhere but in every class where I did something and PHPstorm showed errors.
(All those underlined methods got annoying and I like my auto-complete :smile:)

##### CustomColumns in list view

I updated the normal and bootstrap templates (and the `getJSON()` script) so that you can define CustomColumns that are shown in the normal tabular list view

To define the there is a new config setting (similar to `cops_calibre_custom_column`):

~~~
    /*
     * Custom Columns for the list representation
     * to add as an array containing the lookup names configured in Calibre
     *
     * For example : array ("genre", "mycolumn");
     *
     * Note that the custom olumn type "comment" is not supported
     */
    $config['cops_calibre_custom_column_list'] = array();
~~~

##### CustomColumns in details view

I did the same for the Book details view

And again there is a new configuration option.
I wanted to separate which columns are show on the index page (`cops_calibre_custom_column`), which are shown in the list view (`cops_calibre_custom_column_list`) and which are shown in the details view (`cops_calibre_custom_column_preview`).
For example it doesn't make sense to show the Word Count on the index page, because I'm pretty sure for every count there is only one book.
And it doesn't make sense to show long comment columns in the list view, they would only take too much space.
So I made all of the three places individually configurable

~~~
    /*
     * Custom Columns for the book preview panel
     * to add as an array containing the lookup names configured in Calibre
     *
     * For example : array ("genre", "mycolumn");
     *
     * Note that the custom olumn type "comment" is not supported
     */
    $config['cops_calibre_custom_column_preview'] = array();

~~~

##### Unit tests

All the stuff I did has an unit test in CustomColumnsTest.php (*customcolumns.php* is at 95% coverage)

Also there was a bug in another unit test if the project path had spaces in them (the parameter of `java -jar` was not enclosed n quotes), I fixed that too because I had a space in my project path. (see 4f4945b)

Greetings
  ~ Mike

### CODE REVIEW

**Comment by chadberg** [comment]
I see you and I have a similar notion of using a binary 'read' column. This pull is working well for me.

**Comment by seblucas** [comment]
Sorry for the delay, I've had some personal stuff to take care of :(.

Anyway thanks for your huge work. It feels good to see my work read and corrected by people who are way better at writing PHP than me ;). I've updated a branch locally to test but it feels very well done.

**Comment by Mikescher** [comment]
> Sorry for the delay, I've had some personal stuff to take care of :(.

yeah no problem, personal stuff is always more important :)
And I also have not as much time for personal coding as I would like...

**Comment by Horla** [comment]
@Mikescher I have set some columns with text (http://www.mobileread.com/forums/showpost.php?p=3352831&postcount=1291). It works great on the homepage. For example, one of my columns is called "test_colonne" and it contains two different categories (essai1 and essai2).

But when I go on the preview page, it only shows digits. What should I do to get the text on the book preview (essai1 or essai2)?

image
image

**Comment by seblucas** [comment]
I don't use any custom column myself, but I remember testing it on a side library without any problem. I'll check that again

**Comment by Mikescher** [comment]
Hi @Horla:

>  I have created the ISBN column following the calibre way (I clicked on « ISBN »). Is this type of column supported or does it fall inside the "composite custom columns" category?

Yeah the ISBN example uses composite columns, they are currently not supported (and I don't think they will ever be, because they are ... complex)

> I have added custom columns this way:
> ~~~~~~
> $config['cops_calibre_custom_column_list'] = array("test","source","type"); 
> $config['cops_calibre_custom_column_preview'] = array ("test","source","type");
> $config['cops_calibre_custom_column'] = array ("test","source","type");
> ~~~~~
> For example, inside the "type" column I have : fiction, non-fiction. On the homepage it works great, I can navigate inside "fiction" and "non-fiction". However when it display the booklist and the preview, it doesn't display the text (fiction or non-fiction), it displays digits (1, 2).
> 
> What shoudl I do so that it displays the text?

Yep thats a bug (displaying the ID instead of the actual text), I made a pull request that fixes that: #285

> I have tried to add "size" inside the array of the custom_column lines, but it didn't work. Am I missing something? 

Size is not a custom column, it's just a normal calibre column and COPS currently does not display its value

Greets
~ Mike

**Pull request merged**
