### PR TITLE
Translations update 01May2017

### PR DESCRIPTION
**Pull request by horus68**
Sync files from Transifex. Translations update 01May2017

### CODE REVIEW

**Comment by seblucas** [comment]
Thanks a lot for your speedy answer ;)

There is a conflict for the italian file, did you update you branch before doing the PR ?

**Comment by horus68** [comment]
There is a strange conflict on italian language!
My local file do not have issues 
`"seriesword.none": "Nessuna serie",`
is now change to 
`"seriesword.none": "Nessuna collana",`
but it do not merge into online github.
Can you sort it out?

**Comment by horus68** [comment]
If you can please merge my committed file for italian into the previous one online (or merge all the conflicts)

**Comment by seblucas** [comment]
Committed locally.

@horus the master branch of your fork is quite old, that should be why there was a conflict. You should update it (or delete it and refork as you prefer).

**Pull request closed without merging**
