### PR TITLE
Support for virtual libraries

### PR DESCRIPTION
**Pull request by Broele**
**This is not a finished solution, but just a first step!**
Calibre supports to create virtual libraries that contain only a subset of all books. I am interested and willing to add this feature to cops (see feature request #204). Since I am new to this project, I would like to get some feedback and see if someone else is already working on it. With this pull request, I want to start a dialog about how to add this feature.

My current thoughts that I put here for discussion:
- For the user, virtual libraries look like databases
- Internally, the $database parameter has to be modified to hold two values (database and virtual library). If just one parameter is used, the database id doesn't directly relate to one database file.
- To apply the filter of a virtual library, the filter has to be translated into SQL-Terms. To use this, the existing sql statements might have to be modified.

_And if that works:_ 
allow to add virtual libraries into the database name. E.g. like this:

``` php
$config['calibre_directory'] = '/volume1/books/@Programming'
```

In combination with user-specific config-files, this would restrict certain users to certain libraries (e.g. kids to child books)

The current code only reads the virtual library names and shows them as independent databases. No filtering or adjusted counting is done, yet.

### CODE REVIEW

**Comment by Broele** [comment]
I created a small database with two virtual libraries for testing purposes. You can find it under https://www.dropbox.com/s/rb9u9upozlb0hzy/metadata.db?dl=0
Remember to set
```php
$config['enable_virtual_libraries'] = 1;
```
in your `config_local.php`.

**Comment by seblucas** [comment]
Thanks for the PR and the topic, I've downloaded your sample library and see how virtual libraries work.

I'll check your PR after.

**Comment by seblucas** [comment]
Ok, I thought a little about that yesterday and I saw some similarities with an almost unknown feature of COPS : opds' facets. Facets allow books to be filtered by tags, most of the work is done in `getFilterString` in `book.php`.

I imagine that virtual libraries can also filter book by series or authors but I guess tags are used most of the time. There's also a difference as using facets won't filter authors, series, ... but will only filter book lists but I guess it's a easy way to test the feature.

**Comment by Broele** [comment]
Thank you for considering my idea. 
I was aware of the method `getFilterString`, but I was not sure when exactly it is used. I am still new to the project and try to get along with it.

I was considering if it is possible to modify the function for the use of virtual libraries, but not all SQL expressions make use of it, so I am afraid, we will need to modify some of the SQL statements to.

For testing purposes, tags will be a good start, but virtual libraries can be more complex, containing series, author, even format and also combinations of them. For myself, it is interesting to have books with any format and books without any format in different virtual libraries (in calibre, I do so), since I also include my printed books into the library, but it's easier to download an ebook without looking at ALL my books.

For the concrete implementation: I was planning to include a method similar to `getFilterString` into the `VirtualLib` class. This function can be extended step by step to support more and more filter terms, but I agree that starting with tags would be a good idea.

Yesterday, I had some time and started to write some more code. For me the logical next step after this PR would be to add another url parameter `vl=` and take it everywhere, where the `db=` parameter goes. This should not change anything, but prepare the code a bit more for the virtual libraries. You can have a look at it here: https://github.com/Broele/cops/tree/feature/vLibs_parameter
I did not merge it into the PR, yet, because I first wanted to see what you think of this first code.

The question is, how shall I further go on? Shall I for the moment develop in this PR until a first version is working? Or do you want to merge the PR when one step is done that doesn't break anything?

**Comment by Broele** [comment]
I changed isMultipleDatabaseEnabled, so that enabling virtual libraries also enables multiple databases and added a small helper function to combine the database name and the name of the virtual libraray into one name.

In parallel, I am working on the new url parameter `vl`. Some of this two commits might be useful for that. @seblucas When I merge the new parameter into this PR, I might need some help, code review and testing. It comes with some more changes at the existing code and I am far from being an expert for it, yet.

**Comment by Broele** [comment]
OK, here comes the next step: transporting the url parameter `vl=` over all links and pages.
I used another branch for it and now it seems the commits somehow mix up with the rest of our discussion. So here is a clear list of the new changes:
* https://github.com/Broele/cops/commit/a1faa2ea43420ca3c444b48ac4228cb6de272f58 (transport vl over most pages)
* https://github.com/Broele/cops/commit/a37a0bfb06b36e72b7693052518c86284b2075ef (I added some changes in the default template that I forgot before)
* https://github.com/Broele/cops/commit/2756093394115ccd5aeb152b9520458973a35f46 (this should bring virtual libraries into the search function)

I think this code need some further work, review and testing. I just see that the automatic tests fail. Could it be, because I did not update the testing scripts?
@seblucas I did not change the URL rewriting code, yet. Is it necessary to update something, there?
In general, the new code should append the vl parameter to (nearly) all links with the default value of 0 (e.g. if virtual libraries are disabled).
I will also test this code some more, but right now it looks good enough to share it in this work-in-progress PR.

And in the end - not related to the code or the PR: Merry Christmas.

**Comment by seblucas** [comment]
Sorry for not speaking much, It's Xmas time and I'm still working for a few hours. Next week I'll be home on vacation, I'll have a look at your code.

Thanks again and merry Xmas to you

**Comment by Broele** [comment]
No need to say sorry. I just had some free time and coding is kind of relaxing for me. I hope you have a good vacation.

I'm right now looking into the database model and the sql statements to get an overview before inserting the filter. But since it is Christmas, I also do not have much time for that. Nevertheless, I assume that my last commits might miss some parts, e.g. url rewriting.

**Comment by Broele** [comment]
I found again some time to work on this. The virtual libraries are stored as calibre search strings. I'm parsing these into an internal representation. The current code just supports simple versions of these search strings, but for the moment that is enough to work with.

**Comment by Broele** [comment]
These are a number of commits from the last days. Basically, it now does basic filtering for books in virtual libraries.

There are still some issues (as the tests show):
- I (temporarily) deactivated the opds facets. I plan to include them into the virtual library filter mechanism. If I understand it in the right way, this is, what breaks the tests.
- I did not change all database queries, yet. Especially, some numbers show the unfiltered count, while later only filtered results are shown.
- @seblucas I tried to modify the internal id, but I am not sure where they are used for, so I do not know if that is a good idea.

Within the next days, I will put a small example online, to show what this PR does until now.

**Comment by seblucas** [comment]
I'll be on the train this afternoon, I'll check your patches

**Comment by Broele** [comment]
I mainly added
- the support for different filters (e.g. only english books, only books with pdf)
- correct counters (except for recently added books)

**Comment by Broele** [comment]
Upps, I forgot one sql statement...

**Comment by Broele** [comment]
oh, I really thought OPDS facets would now work again, but the automatic tests indicate differently. I will have to have a closer look at the two testing methods that fail. 
When I tried it on my setup, it seemed to work, but I do not have a reader which supports OPDS facets, so I just added the tag url parameter for testing it.

In general, it seems to work now with my setups and testing databases. @seblucas did you find time to have a look at it? I know that it's a big change that touches a lot of code, so I hope I do not create too much work for you with this.

**Comment by seblucas** [comment]
@Broele 

I started to review your commits but you changed a lot of code so it will take some time. I made some small comment about 2 lines so there is a lot to do ;).

I've created a database with a lot a virtual lib, I'll check your branch on it (OPDS, client side rendering and server side) and report here.

**Comment by seblucas** [comment]
I forgot if you want to test the facets on a real OPDS client, I only know of two supporting that feature : Aldiko (Android) and Bluefire (IOS)

**Comment by Broele** [comment]
@seblucas thank you for taking your time to review my code. I'm sorry that it became so much new and changed code, but I saw no better way to bring the virtual libraries into this.

As for the testing: I did some small testing on some sample setups, but mostly in the browser of my computer. I guess it's time for more comprehensive testing, since the code becomes more and more complete. I will setup some more environments and also test it with my new ebook reader (thanks you, christmas :) ) and some reader apps on my tablet.

There are some known open issues:
- I did not have a look at the url rewriting. Maybe some changes have to be done there to transport the vl parameter. 
- Right now, I do not know why the Travis CI build fails. It seems to have a problem with the opds facet filter for recent books, but to me it looks like they are filtered in my setups. I will have a look at this, this evening again.
- There are still some sql queries unfiltered. 
- Virtual libraries with more than one criterium (e.g. tags:"=Science Fiction" or tags:"=Fantasy" ) are not supported, yet.

Shall I leave this untouched for the moment or shall I go on changing the code? I would like to generate as little work for you as possible. For myself, the initial reason was, that I wanted to create two virtual libraries for my own database on my nas. This should work now ;-)

**Comment by seblucas** [comment]
Hi, I've taken some time to test it and it seems to work fine in most of the cases I tried it on.

But I'll prefer to release a version before merging your PR to limit the risks of bug (I would like to label the next release 1.0.0).

I hope you understand ;).

**Comment by Broele** [comment]
Hi,

thank you for testing. Of course I understand that it is a bad idea to make huge code changes shortly before a release.

And there are still some open points for this PR. E.g. the comment I posted today in https://github.com/seblucas/cops/issues/234 refers to something that only exists in my head, yet.
For me it is just good to know that you do not totally disagree with my general approach. If the approach is ok, then I will go on and work further on this.

**Comment by Broele** [comment]
I think, all sql queries, that need a filter, are now filtered by the virtual library. I hope, I did not forget any query.

**Comment by Broele** [comment]
@seblucas I might a little help from you:
I tried the opds facets with Aldiko and it seems to work perfectly fine. Still, the Travis test fails (I hope I read it in the right way and the reason are the opds facets). Unfortunately, I have absolutely no experience with testing for php. Is there a way to perform the tests locally at my computer, so that I can debug them and figure our what's going wrong? Furthermore, it would be nice to remove obvious bugs before committing or pushing changes.

**Comment by seblucas** [comment]
You can install phpunit and simply run it

Did you check the travis log ? `testPageRecent_WithFacets_IncludedTag` and `testPageRecent_WithFacets_ExcludedTag` are the culprit.

**Comment by seblucas** [comment]
You can also download the phar and run it like that : 
```
php phpunit.phar
```

**Comment by Broele** [comment]
@seblucas thank you for your help.

Yes, I saw the travis logs. That's why Aldiko, because is looks like this ist testing the facets. Unfortunately, in Aldiko everything works fine. 

I'm now in the process of setting up PHPUnit. Unfortunately, in my Eclipse environment this takes a while to get everything setup in the right way. As soon as this works, I will try to track down, why the tests fail, but Aldiko can still work with facets.

**Comment by Broele** [comment]
@seblucas I found the problem and I think it only applies to the tests. 

##### This is what I am doing:
- When a new VirtualLib object is created, it includes directly the current opds facet filter into the virtual library filters.
- Similar to the db object, a virtual lib object is only created, if it doesn't exists already

##### This happens during the Tests:
- The tests are subsequently called from the PHPUnit Framework
- Inbetween, the existing VirtualLib object is not destroyed.
- When the tests with the facet filters are called, an VirtualLib object from the previous tests still exists. No new object is created and, thus, the changed `tag` parameter is not embedded into the VirtualLib filter
- The consequence is a failing test

##### And this is the reason it only applies to the tests
- In reality, the `tag` parameter doesn't change during the script execution
- With each new call (link clicked or ajax), a new runtime environment is used. So a new VirtualLib object needs to be created and a changed facet is directly embedded into the filter.

##### What I could do now:
- Create a facet filter that doesn't store the filter, but computes it every time from the current `tag` parameter
- Just ignore the tests
- Change the tests to call `Base::clearDb()` at the end of each function and (in any case a good idea) also remove the virtual library in `Base::clearDb()`

What do you think is the best way?

**Comment by seblucas** [comment]
Hi,

First sorry for the long wait, I'm not sure if I'll merge your PR. But I used a big chunk of your code in the future COPS 2.0. I'll publish the code later (when it's ready)

I checked out your repo and if I understand correctly for now your code will only work if there's not `and` / `or` in Calibre search query ? I saw that you created `CombinationFilter` but it seems to be a work in progress, am I right ?

**Comment by flowgunso** [comment]
What's the status on this PR ?

**Comment by seblucas** [comment]
Impossible to merge as is, so closing it

**Pull request closed without merging**
