### PR TITLE
Transliteration of search text

### PR DESCRIPTION
**Pull request by glls**
with the help of drupal transliteration module (https://www.drupal.org/project/transliteration)

please set:
$config ['cops_normalized_search'] = "1";

Issue 49 (#49) fixed
Goal : search for Honore should return books written by Honoré de Balzac
achieved

### CODE REVIEW

**Comment by seblucas** [comment]
Hi,

Thanks for the PR, I'll check it out on Saturday when I'll be back home.

**Comment by seblucas** [comment]
It would be great if you could split your PR, your modifications to the romanian language file are easy to merge. The rest is not trivial ;).

**Comment by glls** [comment]
thanks, I will

**Comment by glls** [comment]
I don't know hot to split the PR, the Romanian mod. is just two quotes missing from translation strings.
My main contribution is the text transliteration which I tested a lot and will test even more,
please take your time and merge if it works as expected when you can.

**Comment by seblucas** [comment]
Sorry for the delay.

I tested it on my test string (in https://github.com/seblucas/cops/blob/master/test/baseTest.php#L198) and I can see some change : 

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'AAAAAEACEEEEIIIIOEOOOOOEUUUUEYaaaaaeaceeeeiiiioedoooooeuuuueyyuny'
+'AAAAAACEEEEIIIIOEOOOOOUUUUYaaaaaaceeeeiiiioedooooouuuuyyn'
Original
 'ÀÁÂÃÄÅÇÈÉÊËÌÍÎÏŒÒÓÔÕÖÙÚÛÜÝàáâãäåçèéêëìíîïœðòóôõöùúûüýÿñ'
```
I like most changes as the two strings have (almost) the same length with transliteration which is good at least for French. I'll dig some old mail from some russian / slavic users which had some remarks with the normalization and see if I can reproduce some old bugs. Maybe transliteration fixed them ;).

Anyway I think your changes are better that current situation at least for French and most northern Europe languages. some remarks on the code : 
 * You should change the function `normalizeUtf8String` to call `_transliterate`, that way you'll have less code to modify and you'll see some failed unit tests to fix.
 * I think we don't need `mb_strtoupper` anymore as Sqlite's like is case insensitive for latin letters. that should simplify `useNormAndUp`.
 * You should remove completely the code not needed (and avoid to keep it as comment).

Thanks in advance.

**Comment by glls** [comment]
thanks for the comments,
I removed the unused code and changed the `normalizeUtf8String` function as you proposed.
I'm not sure about the need of `mb_strtoupper` and how it behaves in different environments, I guess you are right, but I kept it to be safe.

I cannot reproduce the test you mentioned in phpunit on my imac or windows machine, sorry.
I will check it later on my archlinux development laptop.

keep the excellent work!

**Comment by seblucas** [comment]
Hi,

I never used an Imac in my entire life, so I'll be trying but not guaranties ;)

If you have phpunit installed you just have to run (the --filter is there to ensure only the faulty test are started) : 

```
phpunit --filter BaseTest
```

If for any reason installing phpunit is hard on Mac, you can download the package phpunit.phar and run it like that : 

```
php phpunit.phar --filter BaseTest
```

**Comment by glls** [comment]
I meant that I cannot get the same output you get from phpunit, instead (on macosx) I get:
```
There was 1 failure:

1) BaseTest::testNormalizeUtf8String
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'AAAAAEACEEEEIIIIOEOOOOOEUUUUEYaaaaaeaceeeeiiiioedoooooeuuuueyyuny'
+'???????????????????????????????????????????????????????'

webapps/cops/test/baseTest.php:198

FAILURES!
Tests: 28, Assertions: 38, Errors: 2, Failures: 1.
```

**Comment by seblucas** [comment]
Indeed it's clearer, maybe this [link](http://stackoverflow.com/questions/26435064/phpunit-outputs-only-question-marks) will help.

**Comment by glls** [comment]
hello Sébastien, since the above errors are not related with my code and cops is working as expected, can we move on with the patch, or please tell me what do I have to do so that we close this transliteration issue/feature.
Regards,
George

**Comment by glls** [comment]
Tests OK
I fixed the phpunit errors and tested both transliteration and search functionality in many languages
Also found a nice tool at the unicode.org site [here] (http://unicode.org/cldr/utility/transform.jsp?a=Latin-ASCII&b=%C3%80%C3%81%C3%82%C3%83%C3%84%C3%85%C3%87%C3%88%C3%89%C3%8A%C3%8B%C3%8C%C3%8D%C3%8E%C3%8F%C5%92%C3%92%C3%93%C3%94%C3%95%C3%96%C3%99%C3%9A%C3%9B%C3%9C%C3%9D%C3%A0%C3%A1%C3%A2%C3%A3%C3%A4%C3%A5%C3%A7%C3%A8%C3%A9%C3%AA%C3%AB%C3%AC%C3%AD%C3%AE%C3%AF%C5%93%C3%B0%C3%B2%C3%B3%C3%B4%C3%B5%C3%B6%C3%B9%C3%BA%C3%BB%C3%BC%C3%BD%C3%BF%C3%B1)

**Comment by seblucas** [comment]
Thanks a lot for doing and sorry again for the delay

**Pull request merged**
