### PR TITLE
Update sendtomail.php (handling secure smtp ports other that 465)

### PR DESCRIPTION
**Pull request by ubupl**
Handling secure smtp ports other that 465. Eg. gmx requires port 587/tls.

### CODE REVIEW

**Comment by seblucas** [comment]
Thanks for the PR. I'm on vacation for now, I'll merge it as soon as possible.

**Comment by seblucas** [comment]
Could you add the documentation for this option in [here](https://github.com/seblucas/cops/blob/master/config_default.php#L213-L234) and I'll be happy to merge your PR

**Comment by ubupl** [comment]
Done

**Comment by seblucas** [comment]
Thanks, adding the documentation in this PR would have been better but that's a nitpick

**Pull request merged**
