### PR TITLE
added paging for recent books and added publish date navigation

### PR DESCRIPTION
**Pull request by creatoras**

### CODE REVIEW

**Comment by seblucas** [comment]
Could you check the unit tests

**Comment by mattboban** [comment]
Is there any movement on this as a "published year" section navigation would be very welcomed.
@seblucas  if this PR is stale, would you welcome a new one in this?

**Comment by seblucas** [comment]
Sorry for the delay, I was on vacation.

I would certainly welcome a new PR with proper unit tests. The code is good enough to fit but there are some unrelated changes and some review to do.

**Comment by seblucas** [comment]
Impossible to merge as is so I'll close this

**Pull request closed without merging**
