### PR TITLE
Load external libraries via Composer instead of shipping them directly

### PR DESCRIPTION
**Pull request by mbirth**
External libraries don't need to be shipped with the source code. If you can check out the repo from Git, you can also let [Composer](http://getcomposer.org/) handle the downloads of external libraries. The composer.lock file makes sure the user gets the tested versions.

I removed libraries which can be handled with Composer, configured Composer and changed paths so that the downloaded libraries are used.

### CODE REVIEW

**Comment by mbirth** [comment]
Looks like this needs a `composer install` somewhere in the test script.

**Comment by mbirth** [comment]
Hmm ... I don't know why Scrutinizer complains about missing coverage data. I didn't touch anything there.

**Comment by seblucas** [comment]
Hi Markus,

Sorry for the delay, I'll check that in a few days.

don't worry too much about scrutinizer, travis is way more important.

Thanks for your PR

**Comment by horus68** [comment]
closed but not merged?

**Comment by mbirth** [comment]
@horus68 Yes as I'm currently refactoring the code, I didn't want those changes to pop up here. Also @seblucas seems to be MIA anyways.

**Comment by horus68** [comment]
@mbirth seblucas is merging again today!

**Pull request closed without merging**
